print("How old are you?")
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weight?", end=' ')
weight = input()
print(f"So, you are {age} old, {height} tall, {weight} weight.")
